language: cpp
cache: 
  apt: true
addons:
  apt:
    sources:
    # - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

compiler:
  - g++

env:
  global:
   - JOBS=4

before_install:
 # - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq build-essential cmake git-core
 - sudo apt-get install -qq pkg-config mono-devel
 - sudo apt-get install -qq libreadline6 libreadline6-dev
 # - sudo apt-get install -qq mysql-client libmysqlclient-dev
 # - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
 - sudo apt-get install -qq libssl-dev libssh2-1-dev
 - sudo apt-get install -qq freeglut3 freeglut3-dev libglew1.5 libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev libbz2-1.0 libbz2-dev
 # For boost: we will download and compile boost instead of using prebuild ones, 
 # since statically linking with boost requires the same tool chain, otherwise there will be link errors. 
 ### - sudo add-apt-repository -y ppa:boost-latest/ppa && sudo apt-get update -q && sudo apt-get install -y libboost1.55-all-dev
 - wget http://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.bz2 --no-check-certificate
 - tar --bzip2 -xf boost_1_68_0.tar.bz2
 - cd boost_1_68_0
 - ./bootstrap.sh --help
 - "echo 'using gcc : 4.9 : /usr/bin/g++-4.9 ; ' >> tools/build/src/user-config.jam"
 - sudo ./bootstrap.sh --with-libraries="thread,date_time,filesystem,system,chrono,signals,serialization,iostreams,regex"
 - sudo ./b2 link=static threading=multi variant=release | head -n 100
 - sudo ./b2 install | tail -n 50
 - cd ..
 
before_script:
 - chmod +x ./build_linux.sh 

script: ./build_linux.sh

after_success:
 - git submodule init && git submodule update 
 - mkdir ParaWorld/npl_packages/main -p && rsync -av npl_packages/main ParaWorld/npl_packages --exclude='.git/'
 - redist_zip_name=nplruntime_${TRAVIS_TAG}_${TRAVIS_OS_NAME}_x64.zip
 - mkdir releases -p && tar -cf releases/${redist_zip_name} -C ParaWorld . && ls -l releases
  
deploy:
  provider: releases
  api_key: 
    secure: "X35ES/AEFfkiKSjcz9SZQCaObAVHqqgcdKuKPST0NkmIvqrwob0oil2TqSGceE22bdtYJGZGGfXNV7yjnPrsHSnNEq73P2w8e2cjBqZzIlAb+NPymJl/KWf9vIts0E8AFrEC4HVC0Dsm/k6gQzMD74MlbqU35qJfGP86eQA8TNeb/5HOQzYrPze36rA1/NDYmPkE+BFgWY180FHnW1O84225YA//m8daaARClREst9c7tp8kwpvVdP4KDULZCH7Ce3ssc6VH/XCUyCXXfaXIU+moeFaMx3z/vfEgOuDx+d53r0H5juLmKb91wjnjCgl8i4mVjO5Dcf7VHgrSIxZk2mxDpV16Hki/uxXWxIBGtBrcdcEDKtap5UTMLV1HklfDoII8IGLMz2TSjUdqgFnRr0gzrWsR/HffjNQJcLgulDIY2pkENBmh00E9BQaFxiurKAW2jArEsyNUSKuS3sjanNnbo/xrdtO4tApIAvuRvXArRS+9tmAbervFu207Hc2NVOV/m2gJfBgYFpXPIBWq58YVMMBdrsxp/PqRIl7HWpGqXNYeOdptsQQ+O2vZEiC0m4oPYFo0ordmChH2Tu7jpLUbziCJyc1hEzGsDQtm9JyY5tnVBOvwCh8MXjY8UD8S0n7lsjaIdkwch5BmB7JJbQXla5EcQ3K3qSgb0ttxSTw="
  file:
    - "releases/${redist_zip_name}"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    all_branches: true
    repo: LiXizhi/NPLRuntime

notifications:
  webhooks: https://hook.bearychat.com/=bwBHc/travis/d3c22fbb73065f1d2e79754098608b21
